name: Build Zed
on:
  workflow_dispatch:
    inputs:
      ref:
        required: true
        type: string
        description: 'Zed git ref'
        default: 'main'
run-name: Build Zed for ref ${{ inputs.ref }}
env:
  CARGO_TERM_COLOR: always
permissions: {}
jobs:
  build:
    runs-on: windows-11-arm
    steps:
    - name: Set Git identity
      run: |
        git config --global user.name  "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
    - name: Checkout Zed (${{ inputs.ref }})
      uses: actions/checkout@v6
      with:
        repository: 'zed-industries/zed'
        ref: "${{ inputs.ref }}"
    - name: Checkout Patches
      uses: actions/checkout@v6
      with:
        path: 'patchset'
        sparse-checkout: patches
    - name: Enable long paths
      run: |
        git config --system core.longpaths true
        New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force
    - name: Apply patchset
      run: git am (Get-ChildItem patchset/patches/*)
    - name: Build
      run: cargo build --release -p zed -p cli
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v7.0.1
      with:
        name: zed-windows-arm64-release-${{ inputs.ref }}
        path: target/release/*.exe
        compression-level: 9
